spring:
  application:
    name: demo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #url: jdbc:h2:mem:test
    url: jdbc:h2:file:./data/test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

# 콘솔 로그 출력 패턴 설정 (메서드, 클래스명, 라인번호 포함)
logging:
  level:
    root: INFO
    com.example.demo: ERROR
  pattern:
    console: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %green(%-3level) %blue(%logger{30}.%M:%line) - %msg%n"
